database:
  driver: "postgres"
  dbname: "test_pg_go"
  username: "mamun"
  password: "123"
  host: "postgres_db" # "0.0.0.0" for local dev
  port: "5432"
  log_mode: true

server:
  host: "0.0.0.0"
  port: "8000"
  secret: "secret"
  environment: "dev" #prod
  request:
    timeout: 100

